### ISSUE TITLE
Simple suggestion

### ISSUE THREAD

**Issue by helpvlc** [AXeL-dev/youtube-viewer#16]
Okay Firstly I used to use the following addon
https://github.com/XrXr/YoutubeSubscriptionChecker
Brilliant thing select the channel Like yours comes up on the left new channels in the screen great but a ransomware javascript page screwed my machine and the youtubesubscriptionchecker was taken off the addons site so unfortunately, I have tried I managed to get the addon on my firefox but could never get it to work again I think the database was missing so no database the project couldn't add the channels

SORRY OFF-TOPIC

I have seen your addon am using it it appears to be Reasonable youtubesubscriptionchecker had one thing I think or more features than yours, that yours could benefit from 

That addon had a number place on the icon when a youtube video was discovered.
I would suggest the same thing.

But with that you have the following on the left all , today's videos, recent videos, watch later. I would suggest adding an icon or something to a newly added video on the right-hand side anything at all to show it's a new unseen video.

what i notice at the moment there is no indication of a new video on the addon icon so I have to check if there is a new video..... Or No timer when hovering over the counter on the icon so i would know when the next checking for a video in addon will occur.
That one is needed just nice to know
If you put an icon with a number of new videos found on it similar to a youtube subscription checker. 
Speaking along those lines also with the ability to play a notification sound so you know that a video has arrived as well as a number of the new videos in the addon.... those two things are the main things I have seen that are lacking in the addon apart from that I wish and its because I used youtube subscription checker for so long ..... I wish that when adding videos it was a full-page, not the addon part itself... See I tried adding a channel from the shortcuts area copy the name from the link to paste it
and as you would expect I had to right-click on the bookmark copy the id of the channel name then go over to the addon and then click the search WAIT FOR A BILLION YEARS for the icon to come up or hope the exact name I copied when I click the button was the actual channel. Might be my internet a bit slow..... Anyway if it were a full-screen page you could go between a page and that page or from a bookmark on the page and copy something without leaving the browsers page of the options of the addon and paste the information into a search making it faster than clicking off clicking on the addon 

All of that aside you have a good enough addon that I am going to use it thank you for that I appreciate it

Either way, I miss that addon lol... but yours could do with a visual number on the icon so you don't have to check all the time to see if there is a new video that has uploaded a few new video addons had that feature one of the latest for live streaming is Nowstreaming a twitch one shows 0 and if a stream goes live shows 1 or 2, etc.
an audio notification and a notification on the new video in the addon so it shows up clear that it's a NEW video... 

But these are only suggestions Go your own way and remember Its a good addon as it is suggestions are only that and Thank you for listening to them

Nicely done.... If I had a bit more coding under my belt I would program my own but I'm too lazy to learn. Thank you for making the addon at least you don't HAVE TO BE LOGGED INTO YOUTUBE with your addon so stupid to have to be logged in to see a new video from a YouTuber
### Your environment
Firefox latest version
not sure about anything else
windows 10 16 gigs ram 4.1ghz 8 core
stupid graphics card 730 GeForce SUPPORT ENDING THIS YEAR :-(
* which browser and its version
Firefox 89.0.1 well won't be when I restart I'm not sure what it will be then sorry.

Well, I appreciate your time as I said I hope to see a few more improvements whatever they may be.

**Comment by AXeL-dev** [comment]
wow that's so long to read :laughing: , anyway, i'll have a look at it & give you my feedback later.

**Comment by helpvlc** [comment]
Yeah Ummm i think most of that you already have implemented
was in the addon that i asked about.

All i asked about

The icon and if there are new videso a number on it
YOU HAVE IT

The sound if there are new videos... im not sure.

If there is It should be able to be changed or volume of the sound modifiable.

The recent videos My suggestion instead of a yes icon on the video you
viewed for the video to be removed from the recent video area list
instead of having a already viewed icon.

Keep that already watched icon in the Todays videos and the All areas.

The addon icon When you click because you have new views it shows you
how many new videos there are THATS GREAT.
But after you click on the icon the amount of new videos are gone... :-(

Why not after you click on the icon and view a video take away 1 video
number from that icon??. Combine that with the videos watched being
removed from recent list and not just adding a watched icon then for
me im not sure whatelse you could do
Except taking up an entire page for the videos not just the icon and a
tiny little interface.

But of course YOUR ADDON and you implement whatever you want

:-) :-) :-)

Like i said as long as it works. I'm happy to use it Because its the
only one left where you DONT have to log into youtube to use it THANK
YOU SOOOOOOO MUCH for that

.... This is probably something your doing for fun or experience in
coding and thats fine.
Because its useable and ready to add more features if you want and i
dont see any bugs with it as im using it.

Thanks for the reply and well im not sure if any of this helps to
inspire you to do extra things to your adon
...... EVEN IF NONE OF WHAT I SAID WILL BE IMPLEMENTED......
Maybe i inspired you to put something else in this something else your
working on
:-)

Enjoy your day

**Comment by AXeL-dev** [comment]
I'm not sure if all what you asked for was implemented in `v1.0.0`, but i will close this issue for now since it's a bit old, feel free to open a new one(s) if you see anything missing there.

**Comment by helpvlc** [comment]
well thank you for the email :-)
